"""empty message

Revision ID: 526bc0837bc3
Revises: fbb1bfd92da5
Create Date: 2025-08-16 14:57:16.464323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526bc0837bc3'
down_revision = 'fbb1bfd92da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id', 'planet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
