"""empty message

Revision ID: 9fba3b20b488
Revises: f4e1c5a52d2c
Create Date: 2025-08-16 14:49:46.210066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fba3b20b488'
down_revision = 'f4e1c5a52d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('eyes_color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'height'),
    sa.UniqueConstraint('eyes_color'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
